name: Auto Merge to Master

on:
  push:
    branches:
      - nitin-dev

jobs:
  merge-to-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nitin-dev
        uses: actions/checkout@v4
        with:
          ref: nitin-dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch master branch
        run: git fetch origin master

      - name: Merge nitin-dev into master
        run: |
          git checkout master || git checkout -b master origin/master
          git merge --no-ff origin/nitin-dev --allow-unrelated-histories -m "Auto-merged nitin-dev into master"
          git push origin master
